// Code generated by generate_getters.go; DO NOT EDIT.
package schema

// Getter methods generated from default tags and zero values.

// ======= Getter methods for AdminCreateUserRequest =======
func (r *AdminCreateUserRequest) GetIsAdminOrDefault(defaultValue bool) bool {
	if r.IsAdmin != nil {
		return *r.IsAdmin
	}
	return defaultValue
}

// ======= Getter methods for ErrorResponse =======
func (r *ErrorResponse) GetErrorMessageOrDefault(defaultValue string) string {
	if r.ErrorMessage != nil {
		return *r.ErrorMessage
	}
	return defaultValue
}

// ======= Getter methods for PhotosGetPhotoListParams =======
func (r *PhotosGetPhotoListParams) GetLimitOrDefault(defaultValue int64) int64 {
	if r.Limit != nil {
		return *r.Limit
	}
	return defaultValue
}

func (r *PhotosGetPhotoListParams) GetOffsetOrDefault(defaultValue int64) int64 {
	if r.Offset != nil {
		return *r.Offset
	}
	return defaultValue
}

