// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

var TableNames = struct {
	PhotoExif       string
	PhotoFiles      string
	PhotoTags       string
	Photos          string
	PhotosPhotoTags string
	UserPasswords   string
	Users           string
}{
	PhotoExif:       "photo_exif",
	PhotoFiles:      "photo_files",
	PhotoTags:       "photo_tags",
	Photos:          "photos",
	PhotosPhotoTags: "photos_photo_tags",
	UserPasswords:   "user_passwords",
	Users:           "users",
}
