// Code generated by MockGen. DO NOT EDIT.
// Source: infrastructures/adapters/photo_storage_adapter.go

// Package mock_adapters is a generated GoMock package.
package mock_adapters

import (
	reflect "reflect"

	entities "github.com/famiphoto/famiphoto/api/entities"
	gomock "github.com/golang/mock/gomock"
)

// MockPhotoStorageAdapter is a mock of PhotoStorageAdapter interface.
type MockPhotoStorageAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockPhotoStorageAdapterMockRecorder
}

// MockPhotoStorageAdapterMockRecorder is the mock recorder for MockPhotoStorageAdapter.
type MockPhotoStorageAdapterMockRecorder struct {
	mock *MockPhotoStorageAdapter
}

// NewMockPhotoStorageAdapter creates a new mock instance.
func NewMockPhotoStorageAdapter(ctrl *gomock.Controller) *MockPhotoStorageAdapter {
	mock := &MockPhotoStorageAdapter{ctrl: ctrl}
	mock.recorder = &MockPhotoStorageAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPhotoStorageAdapter) EXPECT() *MockPhotoStorageAdapterMockRecorder {
	return m.recorder
}

// OpenPhoto mocks base method.
func (m *MockPhotoStorageAdapter) OpenPhoto(filePath string) (entities.StorageFileData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenPhoto", filePath)
	ret0, _ := ret[0].(entities.StorageFileData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenPhoto indicates an expected call of OpenPhoto.
func (mr *MockPhotoStorageAdapterMockRecorder) OpenPhoto(filePath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenPhoto", reflect.TypeOf((*MockPhotoStorageAdapter)(nil).OpenPhoto), filePath)
}

// ReadDir mocks base method.
func (m *MockPhotoStorageAdapter) ReadDir(dirPath string) ([]*entities.StorageFileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", dirPath)
	ret0, _ := ret[0].([]*entities.StorageFileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *MockPhotoStorageAdapterMockRecorder) ReadDir(dirPath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*MockPhotoStorageAdapter)(nil).ReadDir), dirPath)
}
