// Code generated by MockGen. DO NOT EDIT.
// Source: usecases/photo_search_usecase.go

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	gomock "github.com/golang/mock/gomock"
)

// MockPhotoSearchUseCase is a mock of PhotoSearchUseCase interface.
type MockPhotoSearchUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockPhotoSearchUseCaseMockRecorder
}

// MockPhotoSearchUseCaseMockRecorder is the mock recorder for MockPhotoSearchUseCase.
type MockPhotoSearchUseCaseMockRecorder struct {
	mock *MockPhotoSearchUseCase
}

// NewMockPhotoSearchUseCase creates a new mock instance.
func NewMockPhotoSearchUseCase(ctrl *gomock.Controller) *MockPhotoSearchUseCase {
	mock := &MockPhotoSearchUseCase{ctrl: ctrl}
	mock.recorder = &MockPhotoSearchUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPhotoSearchUseCase) EXPECT() *MockPhotoSearchUseCaseMockRecorder {
	return m.recorder
}
