// Code generated by MockGen. DO NOT EDIT.
// Source: services/image_process_service.go

// Package mock_services is a generated GoMock package.
package mock_services

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockImageProcessService is a mock of ImageProcessService interface.
type MockImageProcessService struct {
	ctrl     *gomock.Controller
	recorder *MockImageProcessServiceMockRecorder
}

// MockImageProcessServiceMockRecorder is the mock recorder for MockImageProcessService.
type MockImageProcessServiceMockRecorder struct {
	mock *MockImageProcessService
}

// NewMockImageProcessService creates a new mock instance.
func NewMockImageProcessService(ctrl *gomock.Controller) *MockImageProcessService {
	mock := &MockImageProcessService{ctrl: ctrl}
	mock.recorder = &MockImageProcessServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageProcessService) EXPECT() *MockImageProcessServiceMockRecorder {
	return m.recorder
}

// CreatePreview mocks base method.
func (m *MockImageProcessService) CreatePreview(data []byte, orientation int64) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePreview", data, orientation)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePreview indicates an expected call of CreatePreview.
func (mr *MockImageProcessServiceMockRecorder) CreatePreview(data, orientation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePreview", reflect.TypeOf((*MockImageProcessService)(nil).CreatePreview), data, orientation)
}

// CreateThumbnail mocks base method.
func (m *MockImageProcessService) CreateThumbnail(data []byte, orientation int64) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateThumbnail", data, orientation)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateThumbnail indicates an expected call of CreateThumbnail.
func (mr *MockImageProcessServiceMockRecorder) CreateThumbnail(data, orientation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateThumbnail", reflect.TypeOf((*MockImageProcessService)(nil).CreateThumbnail), data, orientation)
}
