// Code generated by MockGen. DO NOT EDIT.
// Source: services/photo_index_service.go

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	reflect "reflect"

	entities "github.com/famiphoto/famiphoto/api/entities"
	gomock "github.com/golang/mock/gomock"
)

// MockPhotoIndexService is a mock of PhotoIndexService interface.
type MockPhotoIndexService struct {
	ctrl     *gomock.Controller
	recorder *MockPhotoIndexServiceMockRecorder
}

// MockPhotoIndexServiceMockRecorder is the mock recorder for MockPhotoIndexService.
type MockPhotoIndexServiceMockRecorder struct {
	mock *MockPhotoIndexService
}

// NewMockPhotoIndexService creates a new mock instance.
func NewMockPhotoIndexService(ctrl *gomock.Controller) *MockPhotoIndexService {
	mock := &MockPhotoIndexService{ctrl: ctrl}
	mock.recorder = &MockPhotoIndexServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPhotoIndexService) EXPECT() *MockPhotoIndexServiceMockRecorder {
	return m.recorder
}

// CreatePreviewImages mocks base method.
func (m *MockPhotoIndexService) CreatePreviewImages(ctx context.Context, photoID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePreviewImages", ctx, photoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePreviewImages indicates an expected call of CreatePreviewImages.
func (mr *MockPhotoIndexServiceMockRecorder) CreatePreviewImages(ctx, photoID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePreviewImages", reflect.TypeOf((*MockPhotoIndexService)(nil).CreatePreviewImages), ctx, photoID)
}

// RegisterPhotoToMasterData mocks base method.
func (m *MockPhotoIndexService) RegisterPhotoToMasterData(ctx context.Context, files entities.StorageFileInfoList) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterPhotoToMasterData", ctx, files)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterPhotoToMasterData indicates an expected call of RegisterPhotoToMasterData.
func (mr *MockPhotoIndexServiceMockRecorder) RegisterPhotoToMasterData(ctx, files interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterPhotoToMasterData", reflect.TypeOf((*MockPhotoIndexService)(nil).RegisterPhotoToMasterData), ctx, files)
}

// RegisterPhotoToSearchEngine mocks base method.
func (m *MockPhotoIndexService) RegisterPhotoToSearchEngine(ctx context.Context, photoID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterPhotoToSearchEngine", ctx, photoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterPhotoToSearchEngine indicates an expected call of RegisterPhotoToSearchEngine.
func (mr *MockPhotoIndexServiceMockRecorder) RegisterPhotoToSearchEngine(ctx, photoID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterPhotoToSearchEngine", reflect.TypeOf((*MockPhotoIndexService)(nil).RegisterPhotoToSearchEngine), ctx, photoID)
}
