// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	PhotoExif     string
	PhotoFiles    string
	Photos        string
	UserPasswords string
	Users         string
}{
	PhotoExif:     "photo_exif",
	PhotoFiles:    "photo_files",
	Photos:        "photos",
	UserPasswords: "user_passwords",
	Users:         "users",
}
